# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: q3.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'q3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08q3.proto\x12\x06MyUber\"F\n\x0bRideRequest\x12\x12\n\nrider_name\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\"\x8a\x01\n\x0cRideResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\x05\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.MyUber.RideResponse.Status\"<\n\x06Status\x12\x18\n\x14SEARCHING_FOR_DRIVER\x10\x00\x12\x18\n\x14NO_DRIVERS_AVAILABLE\x10\x01\"$\n\x11RideStatusRequest\x12\x0f\n\x07ride_id\x18\x01 \x01(\x05\"9\n\x12RideStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0b\x64river_name\x18\x02 \x01(\t\"\x8e\x01\n\x0eGetRideRequest\x12\x0f\n\x07ride_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64river_name\x18\x02 \x01(\t\x12/\n\x07request\x18\x03 \x01(\x0e\x32\x1e.MyUber.GetRideRequest.Request\"%\n\x07Request\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\"\xb7\x01\n\x14RespondToRideRequest\x12\x0f\n\x07ride_id\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x33\n\x06status\x18\x04 \x01(\x0e\x32#.MyUber.RespondToRideRequest.Status\"4\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x01\x12\r\n\tTIMED_OUT\x10\x02\"(\n\x15RideCompletionRequest\x12\x0f\n\x07ride_id\x18\x01 \x01(\x05\")\n\x16RideCompletionResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\x05\x32\x95\x01\n\rRiderServices\x12:\n\x0bRequestRide\x12\x13.MyUber.RideRequest\x1a\x14.MyUber.RideResponse\"\x00\x12H\n\rGetRideStatus\x12\x19.MyUber.RideStatusRequest\x1a\x1a.MyUber.RideStatusResponse\"\x00\x32\xb8\x01\n\x0e\x44riverServices\x12U\n\x17SubscribeToRideRequests\x12\x16.MyUber.GetRideRequest\x1a\x1c.MyUber.RespondToRideRequest\"\x00(\x01\x30\x01\x12O\n\x0c\x43ompleteRide\x12\x1d.MyUber.RideCompletionRequest\x1a\x1e.MyUber.RideCompletionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'q3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RIDEREQUEST']._serialized_start=20
  _globals['_RIDEREQUEST']._serialized_end=90
  _globals['_RIDERESPONSE']._serialized_start=93
  _globals['_RIDERESPONSE']._serialized_end=231
  _globals['_RIDERESPONSE_STATUS']._serialized_start=171
  _globals['_RIDERESPONSE_STATUS']._serialized_end=231
  _globals['_RIDESTATUSREQUEST']._serialized_start=233
  _globals['_RIDESTATUSREQUEST']._serialized_end=269
  _globals['_RIDESTATUSRESPONSE']._serialized_start=271
  _globals['_RIDESTATUSRESPONSE']._serialized_end=328
  _globals['_GETRIDEREQUEST']._serialized_start=331
  _globals['_GETRIDEREQUEST']._serialized_end=473
  _globals['_GETRIDEREQUEST_REQUEST']._serialized_start=436
  _globals['_GETRIDEREQUEST_REQUEST']._serialized_end=473
  _globals['_RESPONDTORIDEREQUEST']._serialized_start=476
  _globals['_RESPONDTORIDEREQUEST']._serialized_end=659
  _globals['_RESPONDTORIDEREQUEST_STATUS']._serialized_start=607
  _globals['_RESPONDTORIDEREQUEST_STATUS']._serialized_end=659
  _globals['_RIDECOMPLETIONREQUEST']._serialized_start=661
  _globals['_RIDECOMPLETIONREQUEST']._serialized_end=701
  _globals['_RIDECOMPLETIONRESPONSE']._serialized_start=703
  _globals['_RIDECOMPLETIONRESPONSE']._serialized_end=744
  _globals['_RIDERSERVICES']._serialized_start=747
  _globals['_RIDERSERVICES']._serialized_end=896
  _globals['_DRIVERSERVICES']._serialized_start=899
  _globals['_DRIVERSERVICES']._serialized_end=1083
# @@protoc_insertion_point(module_scope)
