# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import q3_pb2 as q3__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in q3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiderServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRide = channel.unary_unary(
                '/MyUber.RiderServices/RequestRide',
                request_serializer=q3__pb2.RideRequest.SerializeToString,
                response_deserializer=q3__pb2.RideResponse.FromString,
                _registered_method=True)
        self.GetRideStatus = channel.unary_unary(
                '/MyUber.RiderServices/GetRideStatus',
                request_serializer=q3__pb2.RideStatusRequest.SerializeToString,
                response_deserializer=q3__pb2.RideStatusResponse.FromString,
                _registered_method=True)


class RiderServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRideStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiderServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRide': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRide,
                    request_deserializer=q3__pb2.RideRequest.FromString,
                    response_serializer=q3__pb2.RideResponse.SerializeToString,
            ),
            'GetRideStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRideStatus,
                    request_deserializer=q3__pb2.RideStatusRequest.FromString,
                    response_serializer=q3__pb2.RideStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MyUber.RiderServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MyUber.RiderServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiderServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MyUber.RiderServices/RequestRide',
            q3__pb2.RideRequest.SerializeToString,
            q3__pb2.RideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRideStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MyUber.RiderServices/GetRideStatus',
            q3__pb2.RideStatusRequest.SerializeToString,
            q3__pb2.RideStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DriverServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToRideRequests = channel.stream_stream(
                '/MyUber.DriverServices/SubscribeToRideRequests',
                request_serializer=q3__pb2.GetRideRequest.SerializeToString,
                response_deserializer=q3__pb2.RespondToRideRequest.FromString,
                _registered_method=True)
        self.CompleteRide = channel.unary_unary(
                '/MyUber.DriverServices/CompleteRide',
                request_serializer=q3__pb2.RideCompletionRequest.SerializeToString,
                response_deserializer=q3__pb2.RideCompletionResponse.FromString,
                _registered_method=True)


class DriverServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeToRideRequests(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToRideRequests': grpc.stream_stream_rpc_method_handler(
                    servicer.SubscribeToRideRequests,
                    request_deserializer=q3__pb2.GetRideRequest.FromString,
                    response_serializer=q3__pb2.RespondToRideRequest.SerializeToString,
            ),
            'CompleteRide': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRide,
                    request_deserializer=q3__pb2.RideCompletionRequest.FromString,
                    response_serializer=q3__pb2.RideCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MyUber.DriverServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MyUber.DriverServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeToRideRequests(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/MyUber.DriverServices/SubscribeToRideRequests',
            q3__pb2.GetRideRequest.SerializeToString,
            q3__pb2.RespondToRideRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MyUber.DriverServices/CompleteRide',
            q3__pb2.RideCompletionRequest.SerializeToString,
            q3__pb2.RideCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
